import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import NoteCard from "../components/NoteCard";
import { getSortedNotesData } from "../lib/Notes";
import styles from "../styles/Home.module.css";

export async function getStaticProps(): GetStaticProps {
  const allNotesData = getSortedNotesData();
  return {
    props: {
      allNotesData,
    },
  };
}

export const Home: NextPage = ({ allNotesData }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {allNotesData.map(({ id, creationDate, title, cover }) => (
          <NoteCard key={id} noteFrontMatter={{ title, creationDate, cover }} />
        ))}
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
