import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Masonry from "react-masonry-css";
import Header from "../components/Header";
import NoteCard from "../components/NoteCard";
import { getSortedNotesData } from "../lib/Notes";
import styles from "../styles/Home.module.css";

const breakpointColumns = {
  default: 4,
};

export interface HomeProps {
  allNotesData: any[];
}

export const getStaticProps: GetStaticProps<HomeProps> = async () => {
  const allNotesData = getSortedNotesData();
  return {
    props: {
      allNotesData,
    },
  };
};

export const Home: NextPage<HomeProps> = ({ allNotesData }: HomeProps) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className={styles.main}>
        <Masonry
          breakpointCols={breakpointColumns}
          className={styles.notesGrid}
          columnClassName={styles["notesGrid_column"]}
        >
          {allNotesData.map(({ id, creationDate, title, cover }) => (
            <NoteCard
              noteFrontMatter={{ title, creationDate, cover }}
              noteId={id}
              key={id}
            />
          ))}
        </Masonry>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
